# Copyright (c) BDist Development Team
# Distributed under the terms of the Modified BSD License.
version: "3"

volumes:
  pg_data: {}
  pgadmin_data: {}
  redis_data: {}

services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data:Z
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
    shm_size: "256m"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - workspace-network

  pgadmin:
    image: dpage/pgadmin4:7.8
    restart: always
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@tecnico.pt
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"
    networks:
      - workspace-network

  redis:
    image: redis:7.2
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - workspace-network

  notebook:
    image: ghcr.io/bdist/notebook:2023-11-17
    restart: always
    user: "jovyan:users"
    volumes:
      - ./app:/home/jovyan/app
      - ./images:/home/jovyan/images
      - ./work:/home/jovyan/work
      - ../db-labs/data:/home/jovyan/data
      - ../db-labs/labs:/home/jovyan/labs
    depends_on:
      - postgres
    ports:
      - "8888:8888"
    networks:
      - workspace-network

  app:
    build:
      context: ../bankapi
      dockerfile: Dockerfile.development
    restart: unless-stopped
    volumes:
      - ../bankapi:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://bank:bank@postgres/bank
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_SECRET_KEY: 66342083928cc29310851e51d931ea35ebb4b5747bd2a33e0d06c3d6047c83c8
    ports:
      - "8080:8080"
    networks:
      - workspace-network

networks:
  workspace-network:
    driver: bridge
