# Copyright (c) BDist Development Team
# Distributed under the terms of the Modified BSD License.
version: "3"

volumes:
  pg_data: {}
  pgadmin_data: {}
  redis_data: {}

services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data:Z
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
    shm_size: "256m"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - workspace-network

  pgadmin:
    image: dpage/pgadmin4:8
    restart: always
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@tecnico.pt
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "10000:80"
    networks:
      - workspace-network

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - workspace-network

  notebook:
    image: ghcr.io/bdist/notebook:2023-12-15
    restart: always
    user: "jovyan:users"
    volumes:
      - ./app:/home/jovyan/app
      - ./data:/home/jovyan/data
      - ./images:/home/jovyan/images
      - ./work:/home/jovyan/work
    depends_on:
      - postgres
    environment:
      - JUPYTER_PORT=9999
    ports:
      - "9999:9999"
    networks:
      - workspace-network

  app:
      build:
        context: ./app
        dockerfile: Dockerfile.development
      restart: unless-stopped
      volumes:
        - ./app:/app
      depends_on:
        - postgres
      environment:
        DATABASE_URL: postgres://clinic:clinic@postgres/clinic
        FLASK_APP: app
        FLASK_ENV: development
        FLASK_DEBUG: 1
        FLASK_SECRET_KEY: 66342083928cc29310851e51d931ea35ebb4b5747bd2a33e0d06c3d6047c83c8
      ports:
        - "8080:8080"
      networks:
        - workspace-network

networks:
  workspace-network:
    driver: bridge